#!/bin/bash
# # Setting up MPLS tunnel 2 - out

# Setting up tun1

printf "\nSetting up tunnel on guest\n\n"

ip tun a tun2 mode gre remote 10.0.1.4 local 10.0.1.5
ip addr a 10.0.20.2 dev tun2
ip link set tun2 up
ip rou a 10.0.20.0/24 dev tun2
ip rou a 10.0.10.0/24 dev tun2


# MPLS Encapsulation

printf "MPLS Encapsulation\n\n"

sysctl -w net.mpls.conf.tun2.input=1
sysctl -w net.mpls.conf.lo.input=1
sysctl -w net.mpls.platform_labels=1048575
sysctl -w net.ipv4.conf.all.rp_filter=2

ip rou c 10.0.20.0/24 encap mpls 200 dev tun2
ip rou c 10.0.10.0/24 encap mpls 201 dev tun2

ip -f mpls rou a 300 dev lo

printf "\nEnd.\n"
