#!/bin/bash
# Setting up MPLS tunnel 1 - in

# Setting up tun1

printf "\nSetting up tunnel on host\n\n"

ip tun a tun1 mode gre remote 192.168.56.101 local 192.168.56.1
ip addr a 10.0.10.1 dev tun1
ip link set tun1 up
ip rou a 10.0.10.0/24 dev tun1
ip rou a 10.0.20.0/24 dev tun1
ip rou a 10.0.30.0/24 dev tun1

# MPLS Encapsulation

printf "MPLS Encapsulation\n\n"

sysctl -w net.mpls.conf.tun1.input=1
sysctl -w net.mpls.conf.lo.input=1
sysctl -w net.mpls.platform_labels=1048575
sysctl -w net.ipv4.conf.all.rp_filter=2

ip rou c 10.0.10.0/24 encap mpls 200 dev tun1
ip rou c 10.0.20.0/24 encap mpls 203 dev tun1
ip rou c 10.0.30.0/24 encap mpls 204 dev tun1

ip -f mpls rou a 100 dev lo

printf "\nEnd.\n"






