#!/bin/bash
# Setting up MPLS tunnel 3 - in 

# Setting up tun3

printf "\nSetting up tunnel on host\n\n"

ip tun a tun3 mode gre remote 10.0.1.6 local 10.0.1.5
ip addr a 10.0.30.1 dev tun3
ip link set tun3 up
ip rou a 10.0.30.0/24 dev tun3


# MPLS Encapsulation

printf "MPLS Encapsulation\n\n"

sysctl -w net.mpls.conf.tun3.input=1
sysctl -w net.mpls.conf.lo.input=1
sysctl -w net.mpls.platform_labels=1048575
sysctl -w net.ipv4.conf.all.rp_filter=2

ip rou c 10.0.30.0/24 encap mpls 400 dev tun3
ip -f mpls route add 304 as 400 via inet 10.0.30.2
ip -f mpls route add 301 as 201 via inet 10.0.20.1
ip -f mpls route add 302 as 200 via inet 10.0.20.1


printf "\nEnd.\n"

