#!/bin/bash
# Setting up MPLS tunnel 3 - out

# Setting up tun3

printf "\nSetting up tunnel on guest\n\n"

ip tun a tun3 mode gre remote 10.0.1.5 local 10.0.1.6
ip addr a 10.0.30.2 dev tun3
ip link set tun3 up
ip rou a 10.0.30.0/24 dev tun3
ip rou a 10.0.20.0/24 dev tun3
ip rou a 10.0.10.0/24 dev tun3


# MPLS Encapsulation

printf "MPLS Encapsulation\n\n"

sysctl -w net.mpls.conf.tun3.input=1
sysctl -w net.mpls.conf.lo.input=1
sysctl -w net.mpls.platform_labels=1048575
sysctl -w net.ipv4.conf.all.rp_filter=2

ip rou c 10.0.30.0/24 encap mpls 300 dev tun3
ip rou c 10.0.10.0/24 encap mpls 301 dev tun3
ip rou c 10.0.20.0/24 encap mpls 302 dev tun3

ip -f mpls rou a 400 dev lo
printf "\nEnd.\n"
